from __future__ import annotations

import json
import os
import random
import threading
import time
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any, Dict, List, Tuple, Union

import requests
import yaml
from fastapi import FastAPI, HTTPException, Request
from pydantic import BaseModel, Field
from prometheus_client import CollectorRegistry, Gauge, generate_latest, CONTENT_TYPE_LATEST
from starlette.responses import Response

from anomaly_detector import AnomalyDetector, AnomalyResult
from unsw_nb15_pipeline import UNSWNB15Pipeline

CONFIG_PATH = os.getenv("CONFIG_PATH", "/app/config.yaml")
UNSW_MODEL_PATH = os.getenv(
    "UNSW_MODEL_PATH",
    str(Path(__file__).resolve().parent / "models" / "unsw_nb15_model.joblib"),
)

app = FastAPI(title="NHMF ML Anomaly API", version="1.0.0")

registry = CollectorRegistry()

anomaly_score_gauge = Gauge(
    "nhmf_anomaly_score",
    "Normalized anomaly score generated by the ML module. Higher values indicate more abnormal telemetry.",
    ["metric_name", "target", "model"],
    registry=registry,
)

anomaly_flag_gauge = Gauge(
    "nhmf_anomaly_flag",
    "Binary ML anomaly flag. 1 means anomaly, 0 means normal.",
    ["metric_name", "target", "model"],
    registry=registry,
)

latest_value_gauge = Gauge(
    "nhmf_latest_metric_value",
    "Latest source metric value used by the anomaly detector.",
    ["metric_name", "target"],
    registry=registry,
)

model_trained_gauge = Gauge(
    "nhmf_model_trained",
    "Whether the anomaly detector completed a training/scoring cycle.",
    registry=registry,
)

last_run_gauge = Gauge(
    "nhmf_last_run_timestamp",
    "Unix timestamp of the last anomaly detection run.",
    registry=registry,
)

received_alerts_gauge = Gauge(
    "nhmf_received_alertmanager_alerts_total",
    "Number of alerts received through the Alertmanager webhook since process start.",
    registry=registry,
)

STATE = {
    "results": [],
    "last_error": "",
    "received_alerts": 0,
}

UNSW_STATE = {
    "model": None,
    "path": "",
    "mtime": 0.0,
    "last_error": "",
}


class UNSWPredictionRequest(BaseModel):
    records: Union[Dict[str, Any], List[Dict[str, Any]]] = Field(
        ...,
        description="One UNSW-NB15 feature record or a list of records.",
    )


def load_config() -> dict:
    with open(CONFIG_PATH, "r", encoding="utf-8") as file:
        return yaml.safe_load(file)


def load_unsw_model() -> UNSWNB15Pipeline:
    model_path = Path(UNSW_MODEL_PATH)
    if not model_path.exists():
        raise HTTPException(
            status_code=503,
            detail=(
                "UNSW-NB15 model is not trained yet. Run "
                "`python ml-anomaly/train_unsw_nb15.py` to create the model bundle."
            ),
        )

    mtime = model_path.stat().st_mtime
    if UNSW_STATE["model"] is None or UNSW_STATE["path"] != str(model_path) or UNSW_STATE["mtime"] != mtime:
        try:
            UNSW_STATE["model"] = UNSWNB15Pipeline.load(model_path)
            UNSW_STATE["path"] = str(model_path)
            UNSW_STATE["mtime"] = mtime
            UNSW_STATE["last_error"] = ""
        except Exception as exc:
            UNSW_STATE["model"] = None
            UNSW_STATE["last_error"] = str(exc)
            raise HTTPException(status_code=500, detail=f"Failed to load UNSW-NB15 model: {exc}") from exc

    return UNSW_STATE["model"]


def prometheus_query_range(prom_url: str, query: str, lookback_minutes: int, step_seconds: int, timeout: int) -> dict:
    end = datetime.utcnow()
    start = end - timedelta(minutes=lookback_minutes)

    response = requests.get(
        f"{prom_url.rstrip('/')}/api/v1/query_range",
        params={
            "query": query,
            "start": start.isoformat() + "Z",
            "end": end.isoformat() + "Z",
            "step": str(step_seconds),
        },
        timeout=timeout,
    )
    response.raise_for_status()
    data = response.json()
    if data.get("status") != "success":
        raise RuntimeError(f"Prometheus query failed: {data}")
    return data


def extract_series(data: dict, metric_name: str, target_label: str) -> List[Tuple[str, List[float]]]:
    series_list = []
    for item in data.get("data", {}).get("result", []):
        metric = item.get("metric", {})
        target = metric.get(target_label) or metric.get("instance") or metric.get("target") or "unknown"
        values = []
        for _, value in item.get("values", []):
            try:
                values.append(float(value))
            except (TypeError, ValueError):
                continue
        if values:
            series_list.append((target, values))
    return series_list


def demo_series(metric_name: str) -> List[Tuple[str, List[float]]]:
    """Fallback data for first start when Prometheus has not collected enough metrics yet."""
    base = []
    for i in range(80):
        noise = random.uniform(-0.03, 0.03)
        if "cpu" in metric_name:
            value = 25 + random.uniform(-5, 5)
        elif "memory" in metric_name:
            value = 45 + random.uniform(-4, 4)
        else:
            value = 0.05 + noise
        base.append(value)

    # Add an abnormal tail sometimes to keep demo visible.
    if random.random() < 0.35:
        for i in range(5):
            base[-(i + 1)] = base[-(i + 1)] * random.uniform(3.0, 6.0) + random.uniform(0.1, 0.4)

    return [("demo-target", base)]


def run_detection_once() -> None:
    config = load_config()
    prom_cfg = config["prometheus"]
    model_cfg = config["model"]
    runtime_cfg = config.get("runtime", {})

    detector = AnomalyDetector(
        algorithm=model_cfg.get("algorithm", "isolation_forest"),
        contamination=float(model_cfg.get("contamination", 0.08)),
        random_state=int(model_cfg.get("random_state", 42)),
        anomaly_threshold=float(model_cfg.get("anomaly_threshold", 0.65)),
    )

    results: List[AnomalyResult] = []
    try:
        for metric_cfg in config["metrics"]:
            metric_name = metric_cfg["name"]
            query = metric_cfg["query"]
            target_label = metric_cfg.get("target_label", "instance")
            try:
                data = prometheus_query_range(
                    prom_cfg["url"],
                    query,
                    int(prom_cfg.get("lookback_minutes", 60)),
                    int(prom_cfg.get("step_seconds", 30)),
                    int(prom_cfg.get("query_timeout_seconds", 10)),
                )
                series_list = extract_series(data, metric_name, target_label)
            except Exception as exc:
                STATE["last_error"] = f"{metric_name}: {exc}"
                if runtime_cfg.get("demo_mode_if_prometheus_unavailable", True):
                    series_list = demo_series(metric_name)
                else:
                    series_list = []

            min_points = int(model_cfg.get("min_points", 30))
            for target, values in series_list:
                if len(values) < min_points:
                    continue
                result = detector.score_series(metric_name, target, values)
                results.append(result)

                anomaly_score_gauge.labels(result.metric_name, result.target, result.model).set(result.score)
                anomaly_flag_gauge.labels(result.metric_name, result.target, result.model).set(result.flag)
                latest_value_gauge.labels(result.metric_name, result.target).set(result.latest_value)

        model_trained_gauge.set(1 if results else 0)
        last_run_gauge.set(time.time())
        STATE["results"] = [r.__dict__ for r in results]
    except Exception as exc:
        STATE["last_error"] = str(exc)
        model_trained_gauge.set(0)


def background_loop() -> None:
    while True:
        config = load_config()
        run_detection_once()
        time.sleep(int(config.get("runtime", {}).get("refresh_seconds", 30)))


@app.on_event("startup")
def startup() -> None:
    thread = threading.Thread(target=background_loop, daemon=True)
    thread.start()


@app.get("/health")
def health() -> dict:
    unsw_model_path = Path(UNSW_MODEL_PATH)
    return {
        "status": "ok",
        "service": "ml-anomaly",
        "last_error": STATE["last_error"],
        "result_count": len(STATE["results"]),
        "unsw_model_available": unsw_model_path.exists(),
        "unsw_model_path": str(unsw_model_path),
    }


@app.get("/results")
def results() -> dict:
    return {"results": STATE["results"], "last_error": STATE["last_error"]}


@app.get("/unsw/model-info")
def unsw_model_info() -> dict:
    model_path = Path(UNSW_MODEL_PATH)
    if not model_path.exists():
        return {
            "available": False,
            "model_path": str(model_path),
            "message": "Train the model with `python ml-anomaly/train_unsw_nb15.py`.",
        }

    model = load_unsw_model()
    return {
        "available": True,
        "model_path": str(model_path),
        "model_type": model.model_type,
        "feature_count": len(model.feature_columns),
        "attack_classes": model.attack_encoder.classes_.tolist(),
        "metrics": model.metrics_,
    }


@app.post("/unsw/predict")
def unsw_predict(payload: UNSWPredictionRequest) -> dict:
    model = load_unsw_model()
    predictions = model.predict_records(payload.records)
    return {"predictions": predictions}


@app.get("/metrics")
def metrics() -> Response:
    return Response(generate_latest(registry), media_type=CONTENT_TYPE_LATEST)


@app.post("/alert-webhook")
async def alert_webhook(request: Request) -> dict:
    payload = await request.json()
    STATE["received_alerts"] += len(payload.get("alerts", []))
    received_alerts_gauge.set(STATE["received_alerts"])
    return {"received": True, "alerts_count": len(payload.get("alerts", []))}
